# Generated by Django 4.1 on 2022-08-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'اکانت کاربر', 'verbose_name_plural': 'اکانت های کاربر'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='معلم است: '),
        ),
    ]
