# Generated by Django 4.1 on 2022-08-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_name_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='ایمیلی برای در دیدرس عموم'),
        ),
    ]
