# Generated by Django 4.1 on 2022-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_team_member',
            field=models.BooleanField(default=False, verbose_name='عضو تیم است'),
        ),
    ]
