# Generated by Django 4.1 on 2022-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_customuser_facebook_customuser_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='github',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='گیت هاب'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reddit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ردیت'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تویتر'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='واتساپ'),
        ),
    ]
