# Generated by Django 4.1 on 2022-08-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_course_description_alter_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(upload_to='media/Courses/video', verbose_name='فایل'),
        ),
    ]
