# Generated by Django 4.1 on 2022-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time_video',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
