# Generated by Django 4.1 on 2022-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_course_time_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time_video',
            field=models.CharField(max_length=20, verbose_name='زمان ویدیو'),
        ),
    ]
