# Generated by Django 4.1 on 2022-08-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_field_language_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='blog.category', verbose_name='حوزه برنامه نویسی'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='course',
            name='field',
            field=models.ManyToManyField(blank=True, null=True, related_name='field', to='blog.field', verbose_name='فریمورک'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/Courses/video', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Courses/image', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, related_name='language', to='blog.language', verbose_name='زبان برنامه نویسی'),
        ),
    ]
