# Generated by Django 4.1 on 2022-09-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.CharField(max_length=100, verbose_name='کاربر'),
        ),
    ]
