# Generated by Django 4.1 on 2022-09-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_contactus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='massage',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
