# Generated by Django 4.1 on 2022-08-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
